// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAUNzKd6H_9eyp5gI_8ZB-Dpau0RH2x0',
    appId: '1:432539760479:web:31c25e790d137c536068ea',
    messagingSenderId: '432539760479',
    projectId: 'mini-lms-kelompok-g',
    authDomain: 'mini-lms-kelompok-g.firebaseapp.com',
    storageBucket: 'mini-lms-kelompok-g.firebasestorage.app',
    measurementId: 'G-Z6L27QD274',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGICxxeL8DT9VpaiaXtGKj7YxJhIyhX18',
    appId: '1:432539760479:android:3753de6f6d7bdf0c6068ea',
    messagingSenderId: '432539760479',
    projectId: 'mini-lms-kelompok-g',
    storageBucket: 'mini-lms-kelompok-g.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk9Kb3kVmRhlLdqEw3Sbsw-zOLaQWoMEU',
    appId: '1:432539760479:ios:f9719af31ce81f796068ea',
    messagingSenderId: '432539760479',
    projectId: 'mini-lms-kelompok-g',
    storageBucket: 'mini-lms-kelompok-g.firebasestorage.app',
    iosBundleId: 'com.example.miniLmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk9Kb3kVmRhlLdqEw3Sbsw-zOLaQWoMEU',
    appId: '1:432539760479:ios:f9719af31ce81f796068ea',
    messagingSenderId: '432539760479',
    projectId: 'mini-lms-kelompok-g',
    storageBucket: 'mini-lms-kelompok-g.firebasestorage.app',
    iosBundleId: 'com.example.miniLmsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAAUNzKd6H_9eyp5gI_8ZB-Dpau0RH2x0',
    appId: '1:432539760479:web:38fe1873490a4c996068ea',
    messagingSenderId: '432539760479',
    projectId: 'mini-lms-kelompok-g',
    authDomain: 'mini-lms-kelompok-g.firebaseapp.com',
    storageBucket: 'mini-lms-kelompok-g.firebasestorage.app',
    measurementId: 'G-B2QBM70VV5',
  );
}
